// Search
export const SEARCH_ADD = 'SEARCH_ADD'
// Product
export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_EDIT = 'PRODUCT_EDIT'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCTS_ALL = 'PRODUCTS_ALL'
export const PRODUCT_GET = 'PRODUCT_GET'
// Checkout
export const CHECKOUT_ADD = 'CHECKOUT_ADD'
export const CHECKOUT_CLEAR = 'CHECKOUT_CLEAR'
export const CHECKOUT_COUNT = 'CHECKOUT_COUNT'
export const CHECKOUT_REMOVE = 'CHECKOUT_REMOVE'
export const CHECKOUT_TOTALCOST = 'CHECKOUT_TOTALCOST'
